[package]
name = "route_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
ctor = "0.4.2"
syn = { version = "2.0.104", features = ["full"]}
quote = "1.0" # Turns syn data structures back into Rust code
