[package]
name = "hello_macro_derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "2.0" # Parses Rust code from a string into a data structure
quote = "1.0" # Turns syn data structures back into Rust code
